### ISSUE TITLE
文档

### ISSUE THREAD

**Issue by HongSiyuan** [any86/vue-create-root#2]
![image](https://user-images.githubusercontent.com/38722610/63822043-ab18bc80-c981-11e9-9783-efbb7d0e7df2.png)

根据文档指示，$createRoot的参数有三个，分别是data, render和options，但是实际看源码，应该是component，data，render和options ，文档容易误导：
![image](https://user-images.githubusercontent.com/38722610/63822140-fcc14700-c981-11e9-8993-f50e86475ea8.png)

----
PS： 想问下$createRoot这个方法能否只用component和options这两个参数，目前如果要使用options的话，中间的data和render参数没办法缺省

**Comment by HongSiyuan** [comment]
此外，这里少了个return哈，导致$createRoot没有返回实例，没办法监听事件了
![image](https://user-images.githubusercontent.com/38722610/63833833-83881b00-c9a6-11e9-8003-f6a20d00a241.png)

**Comment by any86** [comment]
@HongSiyuan  好的十分感谢指正 , 才看到, 抱歉, 我这就改 🐳

**Comment by any86** [comment]
简化参数稍后弄, 我研究下如何抽象成一个复用的功能
